# Generated by Django 5.2.14 on 2026-05-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=20, unique=True, verbose_name='Project ID')),
                ('name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('customer_part_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer Part No')),
                ('pcepl_part_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='PCEPL Part No')),
                ('project_type', models.CharField(max_length=100, verbose_name='Project Type')),
                ('inspection_authority', models.CharField(blank=True, max_length=255, null=True, verbose_name='Inspection Authority')),
                ('applicable_standard', models.CharField(blank=True, max_length=255, null=True, verbose_name='Applicable Standard')),
                ('date_received', models.DateField(verbose_name='Date Received')),
                ('month_received', models.CharField(max_length=50, verbose_name='Month Received')),
                ('target_completion_date', models.DateField(blank=True, null=True, verbose_name='Target Completion Date')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed'), ('Rejected', 'Rejected')], default='Draft', max_length=20, verbose_name='Project Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
