# Generated by Django 5.2.14 on 2026-05-14 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_assigned_employee_project_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer Category')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('alternate_mobile_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Alternate Mobile Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remark/Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Master',
                'verbose_name_plural': 'Customer Masters',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer Name String'),
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.customermaster', verbose_name='Customer'),
        ),
    ]
