# Generated by Django 5.2.14 on 2026-05-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_customermaster_alter_project_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed'), ('Rejected', 'Rejected'), ('Under Review', 'Under Review'), ('Pending Approval', 'Pending Approval')], default='Draft', max_length=20, verbose_name='Project Status'),
        ),
    ]
