# Generated by Django 5.2.14 on 2026-05-14 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workflowstage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='workflowstage',
            name='project',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='WorkflowStage',
        ),
    ]
