# Generated by Django 5.2.14 on 2026-05-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_workflowstage_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Priority'),
        ),
    ]
