# Generated by Django 5.2.14 on 2026-05-17 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_description_project_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_number', models.CharField(max_length=100, unique=True, verbose_name='Standard Number')),
                ('standard_name', models.CharField(max_length=255, verbose_name='Standard Name')),
                ('revision', models.CharField(blank=True, max_length=100, null=True, verbose_name='Revision / Edition')),
                ('release_year', models.IntegerField(blank=True, null=True, verbose_name='Release Year')),
                ('category', models.CharField(choices=[('ISO', 'ISO'), ('IEC', 'IEC'), ('Marine IEC', 'Marine IEC'), ('IP', 'IP'), ('EMC', 'EMC'), ('Defence', 'Defence')], max_length=50, verbose_name='Category')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Standard Master',
                'verbose_name_plural': 'Standards Master',
                'ordering': ['standard_number'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.standardmaster', verbose_name='Standard'),
        ),
    ]
