# Generated by Django 5.2.14 on 2026-05-17 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_standardmaster_project_standard'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionAuthorityMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_id', models.CharField(max_length=100, unique=True, verbose_name='Inspection Authority ID')),
                ('name', models.CharField(max_length=255, verbose_name='Inspection Authority Name')),
                ('category', models.CharField(choices=[('Marine', 'Marine'), ('Customer', 'Customer'), ('QA Agency', 'QA Agency'), ('Internal', 'Internal'), ('Defence', 'Defence')], max_length=50, verbose_name='Category')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Person')),
                ('approval_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Approval Type')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20, verbose_name='Status')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_authorities', to='projects.standardmaster', verbose_name='Applicable Standard / Agency')),
            ],
            options={
                'verbose_name': 'Inspection Authority Master',
                'verbose_name_plural': 'Inspection Authorities Master',
                'ordering': ['authority_id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='inspection_authority_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.inspectionauthoritymaster', verbose_name='Inspection Authority FK'),
        ),
    ]
