# Generated by Django 5.2.14 on 2026-05-18 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_inspectionauthoritymaster_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ECN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecn_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='ECN Number')),
                ('raised_department', models.CharField(max_length=255, verbose_name='ECN Raised Department')),
                ('change_initiated_by', models.CharField(max_length=255, verbose_name='Change Initiated By')),
                ('ecn_date', models.DateField(verbose_name='ECN Date')),
                ('old_revision_no', models.CharField(max_length=50, verbose_name='Old Revision No.')),
                ('old_revision_date', models.DateField(blank=True, null=True, verbose_name='Old Revision Date')),
                ('new_revision', models.CharField(max_length=50, verbose_name='New Revision')),
                ('details_of_change', models.JSONField(blank=True, default=list, verbose_name='Details of Change')),
                ('impact_analysis', models.JSONField(blank=True, default=list, verbose_name='Impact Analysis')),
                ('action_plan', models.JSONField(blank=True, default=list, verbose_name='Action Plan')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Reviewed', 'Reviewed'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=20, verbose_name='ECN Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecns_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecns_initiated', to=settings.AUTH_USER_MODEL, verbose_name='Initiator')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecns', to='projects.project', verbose_name='Project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecns_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
            options={
                'verbose_name': 'Engineering Change Request',
                'verbose_name_plural': 'Engineering Change Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
