# Generated by Django 5.2.14 on 2026-05-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_ecn'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='planned_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Planned Start Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_complexity',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10, verbose_name='Project Complexity'),
        ),
    ]
