# Generated by Django 5.2.14 on 2026-06-03 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_planned_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_no', models.CharField(default='DD-F-11', max_length=50, verbose_name='Form No.')),
                ('form_revision_no', models.CharField(default='Rev-00', max_length=50, verbose_name='Form Revision No.')),
                ('form_issue_date', models.DateField(default='2025-07-01', verbose_name='Form Issue Date')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer Name')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product / Project Name')),
                ('customer_drawing_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer Part / Drawing Number')),
                ('pcepl_part_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='PCEPL Part Number')),
                ('panel_dispatch_date', models.DateField(blank=True, null=True, verbose_name='Panel / Product Dispatch Date')),
                ('feedback_collection_date', models.DateField(blank=True, null=True, verbose_name='Feedback Collection Date')),
                ('usage_duration_months', models.PositiveIntegerField(blank=True, default=12, null=True, verbose_name='Usage Duration (Months)')),
                ('performance_feedback', models.JSONField(blank=True, default=list, verbose_name='Performance Feedback')),
                ('customer_rep_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer Rep Name')),
                ('customer_rep_signature', models.TextField(blank=True, null=True, verbose_name='Customer Rep Signature')),
                ('customer_rep_date', models.DateField(blank=True, null=True, verbose_name='Customer Rep Sign Date')),
                ('pcepl_rep_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='PCEPL Rep Name')),
                ('pcepl_rep_signature', models.TextField(blank=True, null=True, verbose_name='PCEPL Rep Signature')),
                ('pcepl_rep_date', models.DateField(blank=True, null=True, verbose_name='PCEPL Rep Sign Date')),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Pending', 'Pending'), ('Submitted', 'Submitted')], default='Scheduled', max_length=20, verbose_name='Status')),
                ('scheduled_date', models.DateField(verbose_name='Scheduled Date')),
                ('notified', models.BooleanField(default=False, verbose_name='Notified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Customer Feedback',
                'verbose_name_plural': 'Customer Feedbacks',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
