# Generated by Django 5.2.14 on 2026-06-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_customerfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecn',
            name='old_revision_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Old Revision No.'),
        ),
    ]
