# Generated by Django 5.2.14 on 2026-06-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_ecn_old_revision_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecn',
            name='attachments',
            field=models.JSONField(blank=True, default=list, verbose_name='Attachments'),
        ),
    ]
