# Generated by Django 5.2.14 on 2026-05-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_department_user_employee_id_user_remarks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='PCEPL ERP System', max_length=255)),
                ('financial_year', models.CharField(default='2024-2025', max_length=50)),
                ('system_version', models.CharField(default='v1.0.4-stable', max_length=20)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('server_info', models.CharField(default='Production Node 01 - Windows Server', max_length=255)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
    ]
