# Generated by Django 5.2.14 on 2026-05-14 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_systempermission_delete_rolepermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemPermission',
        ),
    ]
