# Generated by Django 5.2.14 on 2026-05-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_companyprofile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='audit_logs_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
