# Generated by Django 5.2.14 on 2026-05-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='watermark_released',
            field=models.CharField(default='RELEASED', max_length=255),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='watermark_under_approval',
            field=models.CharField(default='UNDER APPROVAL', max_length=255),
        ),
    ]
