# Generated by Django 5.2.14 on 2026-06-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_tabs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
