# Generated by Django 5.2.14 on 2026-06-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_user_allowed_tabs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Admin Code'),
        ),
    ]
