# Generated by Django 5.2.14 on 2026-06-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_user_admin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'SuperAdmin'), ('ADMIN', 'Admin'), ('SUPERVISOR', 'Supervisor'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20),
        ),
    ]
