# Generated by Django 5.2.14 on 2026-05-12 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_created_by_alter_project_month_received_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Locked', 'Locked'), ('Unlocked', 'Unlocked'), ('In Progress', 'In Progress'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Locked', max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_stages', to='projects.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StageActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stage_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workflow.stageinstance')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StageSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='workflow.stageinstance')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_role', models.CharField(choices=[('ADMIN', 'Admin'), ('SUPERVISOR', 'Supervisor'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20)),
                ('approval_required', models.BooleanField(default=True)),
                ('allow_attachments', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stage_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stage Template',
                'verbose_name_plural': 'Stage Templates',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='stageinstance',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.stagetemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='stageinstance',
            unique_together={('project', 'template')},
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Textarea'), ('number', 'Number'), ('email', 'Email'), ('phone', 'Phone'), ('dropdown', 'Dropdown'), ('multi_select', 'Multi Select'), ('checkbox', 'Checkbox'), ('radio', 'Radio Button'), ('date', 'Date Picker'), ('file', 'File Upload'), ('grid', 'Table/Grid Input'), ('boolean', 'Boolean Switch')], max_length=20)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('min_length', models.IntegerField(blank=True, null=True)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('is_readonly', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
                ('options', models.JSONField(blank=True, default=list, help_text='For dropdowns, radio, multi-select')),
                ('stage_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='workflow.stagetemplate')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('stage_template', 'name')},
            },
        ),
    ]
