# Generated by Django 5.2.14 on 2026-05-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_formsection_formfield_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='section',
            field=models.CharField(blank=True, help_text='Grouping name to divide the form into sections', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='FormSection',
        ),
    ]
