# Generated by Django 5.2.14 on 2026-05-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_alter_formfield_section_delete_formsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='configuration',
            field=models.JSONField(blank=True, default=dict, help_text="For grid/table: {'columns': [], 'rows': []}"),
        ),
    ]
