# Generated by Django 5.2.14 on 2026-05-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_formfield_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageinstance',
            name='status',
            field=models.CharField(choices=[('Locked', 'Locked'), ('Unlocked', 'Unlocked'), ('In Progress', 'In Progress'), ('Submitted', 'Submitted'), ('Pending Approval', 'Pending Approval'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Locked', max_length=20),
        ),
        migrations.AlterField(
            model_name='stagesubmission',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=20),
        ),
    ]
