# Generated by Django 5.2.14 on 2026-05-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_alter_stageinstance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageinstance',
            name='actual_completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Actual Completion Date'),
        ),
        migrations.AddField(
            model_name='stageinstance',
            name='delay_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Delay (Days)'),
        ),
        migrations.AddField(
            model_name='stageinstance',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (Days)'),
        ),
        migrations.AddField(
            model_name='stageinstance',
            name='planned_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Planned End Date'),
        ),
        migrations.AddField(
            model_name='stageinstance',
            name='planned_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Planned Start Date'),
        ),
        migrations.AddField(
            model_name='stageinstance',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='stagetemplate',
            name='duration_high',
            field=models.PositiveIntegerField(default=5, verbose_name='Duration (High Complexity) in Days'),
        ),
        migrations.AddField(
            model_name='stagetemplate',
            name='duration_low',
            field=models.PositiveIntegerField(default=1, verbose_name='Duration (Low Complexity) in Days'),
        ),
        migrations.AddField(
            model_name='stagetemplate',
            name='duration_medium',
            field=models.PositiveIntegerField(default=3, verbose_name='Duration (Medium Complexity) in Days'),
        ),
    ]
